### ISSUE TITLE
No Response when trying to view camera

### ISSUE THREAD

**Issue by dmcgrew** [KhaosT/homebridge-nest-cam#1]
I just installed this and I think it’s almost working. I can see a static image of my camera in homekit but when I tap on it homekit says No Response. I am running homebridge on a Pi Zero. I noticed that when I try to view the camera that my Pi’s CPU usage goes to 100%. When I close the Home app the CPU usage goes back down to like 5%. Is it possible that the Pi Zero is too weak to run this? I’m guessing there’s some video processing going on with ffmpeg and that might be a little too much for my little Zero to handle.

**Comment by KhaosT** [comment]
Yeah, Raspberry Pi’s CPU is too weak to handle transcoding properly. I’ll try to push an update later today to offer an option to use OMX hardware acceleration on Raspberry Pi.

**Comment by dmcgrew** [comment]
Ok cool. Check out this comment on Reddit too.. https://www.reddit.com/r/HomeKit/comments/7fncev/nest_cams_finally_have_a_homebridge_plugin_use/

**Comment by KhaosT** [comment]
Alright, 0.0.3 has the OMX option now. You may need a special ffmpeg to use that.
