### ISSUE TITLE
Sound?

### ISSUE THREAD

**Issue by jagpreetbatth** [KhaosT/homebridge-nest-cam#10]
I am getting live feed and it is very stable but not sound?
Any ideas why??

**Comment by KhaosT** [comment]
Yeah, sound and speak back is not supported by this plugin yet.

**Comment by jagpreetbatth** [comment]
ahhh I see, THANKS k.T.

**Comment by leoneleone** [comment]
@KhaosT 

Any plans to support Sound (Speaker + Mic) soon?

Thanks so much for the great plugin. I, like most, have been waiting years for this.
Thank you so much 😊

**Comment by jagpreetbatth** [comment]
Yes!! Second that! Please please add mic and sound! Plz!
