### ISSUE TITLE
Whats the 8 digit configuration code?

### ISSUE THREAD

**Issue by maartenvant** [KhaosT/homebridge-nest-cam#15]
Everything is running perfectly, no errors in the terminal. 

When I want to add I click on + and click on "no code or or unable to scan" and I see the cam below the nearby accessories. When I click on the cam it is asking me the 8 digit HomeKit-configurationcode....

What the code and where can I find it

**Comment by pauloruberto** [comment]
It is the same code as the configuration code for homebridge.

**Comment by maartenvant** [comment]
Maybe I completely overlooked this, but where can I find the 8 digit code (HomeKit-configurationcode)?

The 'homebridge' description only talks about <When you attempt to add Homebridge, it will ask for a "PIN code". The default code is 031-45-154>.

But the PIN is a 9 digit code with < - > in between. HomeKit-configurationcode should be 8digits <12345678>.

Can I just change this in the 'config.json' ?

**Comment by pauloruberto** [comment]
The default code is also 8 digits, not 9 haha. If you enter that code, the camera can connect. It is displayed when you first start up homebridge, and you can change the code at the top of the config.json file if you want.

**Comment by maartenvant** [comment]
Got it working. thanks
