### ISSUE TITLE
Unable to add Camera accessory after failed (Add Accessory)

### ISSUE THREAD

**Issue by leoneleone** [KhaosT/homebridge-nest-cam#20]
I’ve run into a small problem:

I have a few Nest Cams. Have been able to get your plugin up and running, and was able to add most of my Nest Cams to HomeKit using the Home.app. Unfortunately two of the Nest Cams failed when trying to add them, and now they’re not showing up as available when I try the “Add Accessory” process again. I can see from homebridge output that the plugin is exposing them as available, but they don’t show up in Home.app when I try to Add them. 

How can I make the missing Cameras appear again so I can add them? They were there before the Adding failed (HomeKit Error: “Could not add Accessory”).

Hope someone can help.

**Comment by leoneleone** [comment]
I had

**Comment by justinshuls** [comment]
Same issue
