### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by taimurasad** [KhaosT/homebridge-nest-cam#3]
is this all I need to add under 

"accessories":[ 

{
  "platform": "Nest-cam",
  "username": "user@user.com",
  "password": "pass123",
  "useOMX": true
}

]

cause doing this throws indexof error. any help?

**Comment by KhaosT** [comment]
This is a platform plugin, so it needs to be put in plugin section. Here is an example of full config.json

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "EE:11:33:DD:CE:30",
		"pin": "031-45-154"
	},
	"accessories": [],
	"platforms": [{
		"platform": "Nest-cam",
		"username": "user@user.com",
		"password": "pass123",
		"useOMX": true
	}]
}
```

**Comment by taimurasad** [comment]
That fixed it. thank you so much. working now, well mostly. the problem now is that whenever I try and open the camera preview window into full screen, home bridge crashes with this error:

buffer.js:332
      throw new TypeError('"list" argument must be an Array of Buffers');
      ^

TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:332:13)
    at NexusStreamer._sendMessage (/usr/lib/node_modules/homebridge-nest-cam/lib/streamer.js:139:30)
    at NexusStreamer.requestHello (/usr/lib/node_modules/homebridge-nest-cam/lib/streamer.js:187:10)
    at TLSSocket.self.socket.tls.connect (/usr/lib/node_modules/homebridge-nest-cam/lib/streamer.js:78:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket.<anonymous> (_tls_wrap.js:1109:14)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)


I can see the 10s previews of all cameras I have just fine in smaller windows. just that if I open the window, home bridge crashes.

running home bridge on Pi3 here. Have enabled useOMX to true. any help?

**Comment by KhaosT** [comment]
What node version are you on? I think one of the library is using Uint8Array and Buffer in node.js only added support for concat normal Buffer and Uint8Array in v8.0.

I can probably fix this by create a buffer first...

**Comment by taimurasad** [comment]
you mean the version of home bridge im running? not sure how I can check it. can you tell me the command to check and report back here?

**Comment by KhaosT** [comment]
Node.js version. You can check that with `npm version`.

**Comment by taimurasad** [comment]
{ npm: '4.2.0',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '51',
  node: '7.10.0',
  openssl: '1.0.2k',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.11.0',
  v8: '5.5.372.43',
  zlib: '1.2.11' }

**Comment by KhaosT** [comment]
Yeah it's v7.10 so the buffer concat failed. If you can wait, I'll make a new version fix this from my side. Or you can upgrade to v8.x for now if you want.

**Comment by taimurasad** [comment]
can you tell me the command to update node to 8.0?

**Comment by taimurasad** [comment]
just ran sudo apt-get update and it doesn't appear to have updated node

**Comment by KhaosT** [comment]
That's because nodejs's repo is version dependent. You can follow guide from [here](https://nodejs.org/en/download/package-manager/) to update repo to v8.x.

**Comment by KhaosT** [comment]
Alright v0.0.5 should fix this.

**Comment by KhaosT** [comment]
(If you haven't update node you can just try reinstall this package from npm)

**Comment by taimurasad** [comment]
can confirm that updating to 0.0.5 fixed the issue! thank you so much!

**Comment by KhaosT** [comment]
Great :) also just curious, which Raspberry Pi are you using and does the live video mains an acceptable latency?

**Comment by taimurasad** [comment]
just got around to updating node on my Pi3 as well using the following two commands

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

everything works perfect. streaming works too on my Pi3 with useOMX": true! Thank you so much for this KhaosT. All 6 of my Nest cams are more useful than ever before!

**Comment by taimurasad** [comment]
im using Raspberry Pi 3. Think it's the latest version? As for video quality of stream, it's not that great as I can see pixelated boxes here and there but I guess on Pi 3 that is too be expected. I'll take that for integration into HomeKit. If I need a very high quality stream, can always use the stock Nest app!

**Comment by organiska** [comment]
I tried to follow these steps, but taimurasad’s steps for updating node have turned everything read only. 

As a result I can no longer edit my config.json
I also cannot launch homebridge.

**Comment by organiska** [comment]
To clarify, I typed in:
<curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs>
