### ISSUE TITLE
Nest Cam for Homebridge

### ISSUE THREAD

**Issue by greztaylor** [KhaosT/homebridge-nest-cam#33]
Hi, I'm looking for some support getting Nest Cam for Homebridge up and running on my Mac OSX.

- I already have homebridge installed and working happily with my Nest products using the plugin homebridge-nest-schmittx so I can control my thermostat etc.

- I also control my door locks vie the homebridge-smartthings plugin

Consequently I'm a novice Homebridge user.  I simply can't get my Nest Cam feed into the IOS Home app,

I have installed the plugin homebridge-camera-ffmpeg and homebridge-nest-cam but still can't get the IOS app to see my Nest Cams as Camera (rather they're seen as sensors).

My config/json file looks as attached.  I'm sure this is the place I've screwed up !!

<img width="1662" alt="screenshot 2018-09-08 at 13 25 18" src="https://user-images.githubusercontent.com/36612071/45254143-1af5f780-b36b-11e8-85e2-31f709a5862b.png">

**Comment by KhaosT** [comment]
If you go to Home app, select add accessory, do you see the camera there?

**Comment by greztaylor** [comment]
Hi I can only see them as sensors (not cameras) when I remove the Homebridge (as it’s already added) and add it back in the Home app as an accessory using the Homebridge code.  I’ve installed ffmpeg and the associated plugin (not sure if I need to run anything outside of HomeBridge) !!! Any ideas?

**Comment by KhaosT** [comment]
Can you post the log? Are there any errors in there?

**Comment by greztaylor** [comment]
Is this what you mean by the log? sorry bit of a novice learning as I go !! 
<img width="823" alt="screenshot 2018-09-08 at 17 45 12" src="https://user-images.githubusercontent.com/36612071/45256502-04619780-b38f-11e8-9966-c85abdd93996.png">

**Comment by KhaosT** [comment]
Yeah this log, but from the log it looks like you already have another server running right now?

**Comment by greztaylor** [comment]
Well I have Homebridge running in my mac but I can't get onto my Next cams in the HomeBridge app.  Everything else works - I'm just not sure what I'm missing, if I've failed to install something or my config file is missing something or even If I'm attempting to add the Nest kit incorrectly in the Home app!!! any advice you could provide would be greatly appreciated

**Comment by KhaosT** [comment]
Can you stop the "HomeBridge app" you are talking about and just run homebridge in terminal as you did above and see what's the output look like?

**Comment by greztaylor** [comment]
The Home app I keep referencing is the one on IOS. I’m running HomeBridge in Terminal on Mac OSX which is the outputs I’ve sent

**Comment by KhaosT** [comment]
Okay :) Would you mind to try one more thing for me? Change the port for `Config` plugin from `8080` to `18080` so we can have homebridge properly running instead of having the plugin to trigger an unhandled exception on launch so no meaningful log is being captured...

**Comment by greztaylor** [comment]
Will do !! Just having some tea (English for an evening meal) then I’ll get on the case. Sorry about having to treat me with kid gloves

**Comment by greztaylor** [comment]
Will do !! Just having some tea (English for an evening meal) then I’ll get on the case. Sorry about having to treat me with kid gloves

**Comment by greztaylor** [comment]
okay so I changed the port to 18080 as advised and ran restarted Homebridge
<img width="896" alt="screenshot 2018-09-09 at 11 13 14" src="https://user-images.githubusercontent.com/36612071/45263444-5ce17500-b421-11e8-8fd9-f8949674ee1d.png">

**Comment by KhaosT** [comment]
Are you sure there isn't another homebridge instance running right now? Based on the log it looks something else is running with the homebridge configuration you are using...

**Comment by greztaylor** [comment]
Hi, me again !!! I still can't get this to work !!! my home app sees the Nest Cameras as 'sensors' rather than actual Cameras when I add Homebridge.  When I start Homebridge on my Mac in Terminal this is what I see:

======================================================

Last login: Sat Oct 27 14:56:46 on console
Grahams-Mac-Pro:~ grahamtaylor$ homebridge
[10/28/2018, 1:36:17 PM] Loaded config.json with 0 accessories and 4 platforms.
[10/28/2018, 1:36:17 PM] ---
[10/28/2018, 1:36:17 PM] Loaded plugin: homebridge-camera-ffmpeg
[10/28/2018, 1:36:17 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[10/28/2018, 1:36:17 PM] ---
[10/28/2018, 1:36:17 PM] Loaded plugin: homebridge-config-ui-x
[10/28/2018, 1:36:17 PM] Registering platform 'homebridge-config-ui-x.config'
[10/28/2018, 1:36:17 PM] ---
[10/28/2018, 1:36:17 PM] Loaded plugin: homebridge-nest-cam
[10/28/2018, 1:36:17 PM] Registering platform 'homebridge-nest-cam.Nest-cam'
[10/28/2018, 1:36:17 PM] ---
[10/28/2018, 1:36:18 PM] Loaded plugin: homebridge-nest-schmittx
[10/28/2018, 1:36:18 PM] Registering platform 'homebridge-nest.Nest'
[10/28/2018, 1:36:18 PM] ---
[10/28/2018, 1:36:18 PM] Loaded plugin: homebridge-smartthings
[10/28/2018, 1:36:18 PM] Registering platform 'homebridge-smartthings.SmartThings'
[10/28/2018, 1:36:18 PM] ---
[10/28/2018, 1:36:18 PM] Loading 4 platforms...
[10/28/2018, 1:36:18 PM] [Config] Initializing config platform...
[10/28/2018, 1:36:18 PM] [Config] Spawning homebridge-config-ui-x with PID 1971
[10/28/2018, 1:36:18 PM] [Nest-cam] Initializing Nest-cam platform...
[10/28/2018, 1:36:18 PM] [Nest] Initializing Nest platform...
[10/28/2018, 1:36:18 PM] [Nest] Fetching Nest devices.
[10/28/2018, 1:36:18 PM] [SmartThings] Initializing SmartThings platform...
[10/28/2018, 1:36:18 PM] [SmartThings] Fetching Smart Things devices.
[10/28/2018, 1:36:18 PM] Loading 0 accessories...
Load homebridge-camera-ffmpeg.Camera-ffmpeg
[10/28/2018, 1:36:19 PM] [Config] Using Form Authentication
Error: listen EADDRINUSE :::18080
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at UiServer.<anonymous> (/usr/local/lib/node_modules/homebridge-config-ui-x/src/server.ts:48:17)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/server.js:4:58)

=============================================================

Have you any idea what I'm missing here? I don't think I have two instances of Homebridge running.  Everything works (locks, thermostats etc) I just can't get the darn Cameras to show in the Home app !

Any help you could provide would be great

**Comment by greztaylor** [comment]
Finally got this working - thanks for all your help and innovation

**Comment by pipdog05** [comment]
> Finally got this working - thanks for all your help and innovation

Hi greztaylor - how did you finally get it to work?  I'm a cut and paster - no coding background, so I have no idea what I'm doing on here to try to fix the "motion sensor" cameras that my home kit app sees.  If nothing else, please point me in the right direction. Thanks!

**Comment by betraydan** [comment]
> Finally got this working - thanks for all your help and innovation

@greztaylor I have the same issue only getting the cameras showing up as sensors. How did you fixed this?

**Comment by paul-45** [comment]
I'm actually looking for the exact opposite - I have managed to get Nest Hello camera working in my Homekit using Homebridge and can see live video feed now.  I would like to have the sensor accessory visible so I can create a Homekit automation (light comes on when motion detected).  Does anyone know how to make the sensor for Nest cam appear in Homebridge/Homekit?

**Comment by paul-45** [comment]
> I'm actually looking for the exact opposite - I have managed to get Nest Hello camera working in my Homekit using Homebridge and can see live video feed now. I would like to have the sensor accessory visible so I can create a Homekit automation (light comes on when motion detected). Does anyone know how to make the sensor for Nest cam appear in Homebridge/Homekit?

Worked this out by installing the generic Nest plugin for Homebridge, can see the Nest camera notion sensor now in Homekit... but for some reason motion doesn't trigger anything in Homekit.  I still get the Nest app motion notification though.
