### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by Aidan711** [KhaosT/homebridge-nest-cam#34]
Hello!

I have my Nest system set up with Homebridge and working well. Since I set that up, my cameras have only been sensors and I cannot view the live feed. I discovered this plug in, but I cannot seem to get it to work. I added "Nest-cam" to platforms, but I am getting an unreadable config error. I am also confused as to what to do with ffmpeg. I installed it successfully, but I am kind of confused as to add it in to the config.json (referring to the pre-made you linked in the readme. 

![image1 1](https://user-images.githubusercontent.com/41637856/47191624-7aee9f00-d316-11e8-9ef9-3b18115456ed.jpeg)

**Comment by KhaosT** [comment]
There is an extra comma at the end of the config.

**Comment by KhaosT** [comment]
https://jsonlint.com/ this is your friend :)

**Comment by Aidan711** [comment]
Was just about to post a comment that I fixed it :)

I put everything back into the Home app, but they are coming up as sensors again and not cameras. I have 3 indoor cams and 1 outdoor. What do you think the problem could be? 

Thanks for the speedy reply!

**Comment by Aidan711** [comment]
Figured out the cameras too haha!
Just had to add them as other accessories.
