### ISSUE TITLE
Camera not showing when adding new accessory.

### ISSUE THREAD

**Issue by QandnotU** [KhaosT/homebridge-nest-cam#41]
I deleted the camera accessory when I was troubleshooting the 405 error discussed previously. I have the latest version of the plugin and have added the token to my config. I can't unfortunately get the camera to show when adding new accessory. 

[logfile.log](https://github.com/KhaosT/homebridge-nest-cam/files/2684444/logfile.log)

**Comment by KhaosT** [comment]
`[2018-12-16 20:05:54] [Nest-cam] Create camera - Demi's Room`

So we did find the camera and exposed it to HomeKit. Can you try go to `~/.homebridge/persist` and remove the `AccessoryInfo` for just the camera?

**Comment by QandnotU** [comment]
That did the trick, much appreciated!
