### ISSUE TITLE
getting "[NestCam]Failed to request access token. Unexpected API Error - 403" with 0.0.12

### ISSUE THREAD

**Issue by felsmann** [KhaosT/homebridge-nest-cam#44]
I updated to the new version and retrieved my token the one between "" after "access_token"

Thanks for the help

**Comment by felsmann** [comment]
> Are you sure you used the right access_token? There are two, make sure you use the one started with `b.`

how are they separated?
After "access_token"="lQ...  then there is a /bFy...  but I'm not sure if that's what Im looking for.  I tried that and copied from the b to the last character before the next "/" but same error

**Comment by KhaosT** [comment]
From beginning there is another one.

```
{"2fa_state":"not_enrolled","access_token":"b.xxxxx
```

**Comment by felsmann** [comment]
> From beginning there is another one.
> 
> ```
> {"2fa_state":"not_enrolled","access_token":"b.xxxxx
> ```

OK that was simple, thanks a bunch! no more error!  Now on to figuring out why they are not showing up when I try to add them in HomeKit...

**Comment by KhaosT** [comment]
Did you see the camera if you go to add accessory in Home app?

**Comment by felsmann** [comment]
> Did you see the camera if you go to add accessory in Home app?

No accessories to add. I tapped on "I don't have a code" and normally that's where they would show.  I tried the script on the other thread to confirm the token but no difference...  However the plugin seems to see them:

[12/17/2018, 11:48:56 PM] Back Alley (Back Alley) is running on port 58190.
[12/17/2018, 11:48:56 PM] Front Door (Front Door) is running on port 58191.
[12/17/2018, 11:48:56 PM] Front Patio (Front Patio) is running on port 58192.
[12/17/2018, 11:48:56 PM] Kitchen (Kitchen) is running on port 58193.

**Comment by KhaosT** [comment]
Yeah the plugin clearerly sees the camera. Where are you running the homebridge?

**Comment by felsmann** [comment]
On a Mac

Juan Felsmann 
jfelsmann@gmail.com

On Dec 17, 2018, at 23:58, Khaos Tian <notifications@github.com> wrote:

Yeah the plugin clearerly sees the camera. Where are you running the homebridge?

**Comment by KhaosT** [comment]
Huh... is there by any chance you can try manually remove contents under `~/.homebridge/persist` (Don’t delete the homebridge primary one, only remove the camera accessories).

**Comment by felsmann** [comment]
Thanks a Million! That did it!
