### ISSUE TITLE
[NestCam]Failed to request access token. Unexpected API Error - 403

### ISSUE THREAD

**Issue by Rens93** [KhaosT/homebridge-nest-cam#45]
When I copy and paste:

curl -X "POST" "https://home.nest.com/session" \
     -H 'User-Agent: iPhone iPhone OS 11.0 Dropcam/5.14.0 com.nestlabs.jasper.release Darwin' \
     -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8' \
     --data-urlencode "email=YOUR_NEST_EMAIL" \
     --data-urlencode "password=YOUR_PASSWORD"

I get the next error code:

{"url":"/session","message":"400 Bad Request"}/homebridge #

How can I fix this?

- Ofc. I changed "YOUR_NEST_EMAIL" and "YOUR_PASSWORD" into my own email and password.

**Comment by rtgoodwin** [comment]
Does your password have any strange characters in it? 

Are you submitting that entire command as one long string? If it gets truncated somehow you'll get that kind of response. Or if you've copied and pasted through a weird text editor it might mess with things too...try manually typing the entire thing in at the prompt (I know it's a pain!).

**Comment by Rens93** [comment]
My password contains "@"

**Comment by drewgould** [comment]
I was having the same issue with a $ in my password. I changed my password to remove it and then the command worked.

**Comment by Rens93** [comment]
Just changed my password, but still the samen error:

{"url":"/session","message":"400 Bad Request"}

**Comment by Rens93** [comment]
#CloseMe!

**Comment by staticfade** [comment]
I am currently running the latest version of nest-cam and ffmpeg.  I continue to get the following error:
[Nest-cam] Initializing Nest-cam platform...
[NestCam]Failed to request access token. Unexpected API Error - 403

I have gone through the 2 factor auth and got a access_token and have put this info into my config.json file which looks like this...
"platform" : "Nest-cam",
"access_token":"c.Qjtxxxxxxxxxxxx",
"useOMX": false

I also used the nest plugin and it finds all my nest devices but I still cannot get the nest-cam to work.  any help would be greatly appreciated

**Comment by ChrisChiera** [comment]
Same issue is @staticfade. Same error and also have it set up to use 2 factor access token and everything. It worked previously but stopped working a while ago and finally now starting to look into it. I see that message was in January, did you find a resolution?

**Comment by wjkie** [comment]
I have an access token and the cams were visible and working in the Home app. Seems like the software on the cam was updated to 223-610050 recently and for the last  2 days the camera has not been responding.  I am now getting the following error "[NestCam]Failed to request access token. Unexpected API Error - 403"
