### ISSUE TITLE
Camera Control

### ISSUE THREAD

**Issue by SoaringEagle93** [KhaosT/homebridge-nest-cam#5]
Are we able to turn cameras on and off with this plugin?

**Comment by KhaosT** [comment]
Is there a reason why you need this?

**Comment by SoaringEagle93** [comment]
For the automation side of HomeKit. The nest app is not the best when it comes to Home/Away mode and I feel like this could be used instead.

**Comment by KhaosT** [comment]
For controlling Home/Away mode, I'd suggest you install [homebridge-nest](https://github.com/KraigM/homebridge-nest) as it offers motion alert + home/away control. This plugin is mainly focused on exposing the camera part of Nest product.
