### ISSUE TITLE
Pi 3 - Hardware acceleration seems not working

### ISSUE THREAD

**Issue by titoudoc** [KhaosT/homebridge-nest-cam#50]
Hi, first of all, thanks for your hard work ! It's wonderful to be able to use the Nest Cam and Hello in HomeKit with your homebridge plugin.

I run into some kind of issue. Wether the UseOMX is set to true or false, it seems there is no upgrade in performance. The live stream remain extremely slow. I don't know what else could I try... any help would be greatly appreciated.

I've compiled FFmpeg with h264_omx following this Wiki : https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Raspberry-PI.

My build is fine as confirmed with the command `./ffmpeg -encoders | grep h264_omx` returning `ffmpeg version N-92786-g4096c670ab Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --prefix=/usr/local --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
  libavutil      56. 25.100 / 56. 25.100
  libavcodec     58. 42.104 / 58. 42.104
  libavformat    58. 25.100 / 58. 25.100
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 46.101 /  7. 46.101
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
 V..... h264_omx             OpenMAX IL H.264 video encoder (codec h264)`.

My config.json is the following 
`{
            "platform": "Nest-cam",
            "access_token": "NA",
            "useOMX": true,
        }`

Any idea how to improve live stream ?
Thanks in advance.

**Comment by titoudoc** [comment]
After further test, hardware acceleration is working... but the video is very slow. Probably not enough horse power on the Pi to transcode the video stream...
Any way to improve this ?

**Comment by KhaosT** [comment]
I'm afraid not...

**Comment by titoudoc** [comment]
I've update to version 0.017 and update config.json and it's near perfect, almost fluid !
Thanks !
