### ISSUE TITLE
{"url":"/session","message":"400 Bad Request"}/homebridge #

### ISSUE THREAD

**Issue by Rens93** [KhaosT/homebridge-nest-cam#52]
How can I solve this error ?
I have already changed my password without special symbol..

**Comment by potmat** [comment]
Not sure if this is your issue.  But I got the problem by copy/pasting the curl code into a text editor to modify the username and password.  The text editor I used replaced the double quote characters with curly quotes.

**Comment by Rens93** [comment]
#CloseMe!
