### ISSUE TITLE
Live video fails (but still image appears) on 0.0.14

### ISSUE THREAD

**Issue by agruen** [KhaosT/homebridge-nest-cam#54]
Hello --

Been racking my brain to figure out what's wrong, and can't sort it, so posting an issue.  

In essence, I get a still image from my NestCam (it's a DropCam Pro model), but can't get live video.  I'm running version 0.0.14 of homebridge-nest-cam on a Raspberry Pi 3 B.

My config.json is set to:

> {
>             "platform": "Nest-cam",
>             "access_token": "xxxxxxxxxxxxx",
>             "useOMX": true
> }

*\*My access token (omitted here) works, as I can see the still image...*

The logs show:

> [NexusStreamer]Connected
> [NexusStreamer]OK
> [NexusStreamer]Playback Begin
> undefined
> [NexusStreamer]Connection Closed

Which is not exactly helpful...

I'd been running with FFMpeg that I compiled myself to enable OMX... My first thought was that maybe omx was somehow messed up, so I disabled it in the config.

No joy.

So I thought I'd fall back to the copy of FFMpeg known to work, posted by  @legotheboss [goo.gl/gMGA81](https://goo.gl/gMGA81).  Note, however, that the Google URL shortener is down, and that link doesn't work, so I hunted around in @legotheboss's account until I found what appears to be the [original .deb package](https://github.com/legotheboss/YouTube-files/blob/master/ffmpeg_3.1.4-1_armhf.deb) and installed it/re-enabled OMX.  I verified that the build supported OMX:

> pi@raspberrypi:~ $ ffmpeg -h encoder=h264_omx
> ffmpeg version N-81800-gf013ba4 Copyright (c) 2000-2016 the FFmpeg developers
>   built with gcc 4.9.2 (Raspbian 4.9.2-10)
>   configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --enable-omx --enable-omx-rpi
>   libavutil      55. 30.100 / 55. 30.100
>   libavcodec     57. 58.103 / 57. 58.103
>   libavformat    57. 51.100 / 57. 51.100
>   libavdevice    57.  0.102 / 57.  0.102
>   libavfilter     6. 63.100 /  6. 63.100
>   libswscale      4.  1.100 /  4.  1.100
>   libswresample   2.  2.100 /  2.  2.100
>   libpostproc    54.  0.100 / 54.  0.100
> Encoder h264_omx [OpenMAX IL H.264 video encoder]:
>     General capabilities: delay 
>     Threading capabilities: none
>     Supported pixel formats: yuv420p
> h264_omx AVOptions:
>   -omx_libname       <string>     ED.V.... OpenMAX library name
>   -omx_libprefix     <string>     ED.V.... OpenMAX library prefix
>   -zerocopy          <int>        E..V.... Try to avoid copying input frames if possible (from 0 to 1) (default 0)
> 

I tried again.

No joy.

Did a bit more searching and thought maybe I forgot to give my homebridge user access to the video, so I ran:

`sudo usermod -aG video homebridge`

No joy.

Any thoughts?  I'd sure appreciate them!

**Comment by agruen** [comment]
Just a quick update.  After making exactly no changes, this has both started to work, stopped working, and started to work again.  If anyone can point me in the right direction to troubleshoot this, I'd be most appreciative.

**Comment by titoudoc** [comment]
Hello, you've go to add RTSP and compile FFMPEG again : `--enable-protocol=tcp --enable-demuxer=rtsp`.

Let me know if it's fully working, my configuration works but the hardware acceleration doesn't despite  `enable-omx --enable-omx-rpi`.

**Comment by KhaosT** [comment]
Would you mind to manually edit [streamer.js](https://github.com/KhaosT/homebridge-nest-cam/blob/master/lib/streamer.js#L431) and add
```
ffmpeg.stderr.on('data', function(data) {
    console.log(data.toString());
});
```
to there so we can see why it's not streaming?

**Comment by ayn** [comment]
Ah nice:

```
0|homebridge  | ffmpeg version N-92989-g32421602df Copyright (c) 2000-2019 the FFmpeg developers
0|homebridge  |   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
0|homebridge  |   configuration: --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree --enable-protocol=tcp --enable-demuxer=rtsp
0|homebridge  |   libavutil      56. 26.100 / 56. 26.100
0|homebridge  |   libavcodec     58. 44.100 / 58. 44.100
0|homebridge  |   libavformat    58. 26.100 / 58. 26.100
0|homebridge  |   libavdevice    58.  6.101 / 58.  6.101
0|homebridge  |   libavfilter     7. 48.100 /  7. 48.100
0|homebridge  |   libswscale      5.  4.100 /  5.  4.100
0|homebridge  |   libswresample   3.  4.100 /  3.  4.100
0|homebridge  |   libpostproc    55.  4.100 / 55.  4.100
0|homebridge  | Unrecognized option 'x264-params'.
0|homebridge  | Error splitting the argument list: Option not found
```

**Comment by KhaosT** [comment]
Ah I guess `h264_omx` doesn't support that... can you try remove `-x264-params "intra-refresh=1:bframes=0"` from the code and see what's the output?

**Comment by ayn** [comment]
Working now, thanks @KhaosT!

```
0|homebridge  | ffmpeg version N-92989-g32421602df Copyright (c) 2000-2019 the FFmpeg developers
0|homebridge  |   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
0|homebridge  |   configuration: --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree --enable-protocol=tcp --enable-demuxer=rtsp
0|homebridge  |   libavutil      56. 26.100 / 56. 26.100
0|homebridge  |   libavcodec     58. 44.100 / 58. 44.100
0|homebridge  |   libavformat    58. 26.100 / 58. 26.100
0|homebridge  |   libavdevice    58.  6.101 / 58.  6.101
0|homebridge  |   libavfilter     7. 48.100 /  7. 48.100
0|homebridge  |   libswscale      5.  4.100 /  5.  4.100
0|homebridge  |   libswresample   3.  4.100 /  3.  4.100
0|homebridge  |   libpostproc    55.  4.100 / 55.  4.100
0|homebridge  | [NexusStreamer]Connected
0|homebridge  | [NexusStreamer]OK
0|homebridge  | [NexusStreamer]Redirect
0|homebridge  | [NexusStreamer]Redirecting...
0|homebridge  | [NexusStreamer]Connection Closed
0|homebridge  | [NexusStreamer]Connected
0|homebridge  | [NexusStreamer]OK
0|homebridge  | [NexusStreamer]Playback Begin
0|homebridge  | Input #0, h264, from 'pipe:':
0|homebridge  |   Duration: N/A, bitrate: N/A
0|homebridge  |     Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 15 fps, 15 tbr, 1200k tbn, 30 tbc
0|homebridge  | Stream mapping:
0|homebridge  |   Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_omx))
0|homebridge  | [swscaler @ 0x282a870] deprecated pixel format used, make sure you did set range correctly
0|homebridge  | [h264_omx @ 0x27e92d0] Using OMX.broadcom.video_encode
0|homebridge  | Output #0, rtp, to 'srtp://10.0.1.21:50931?rtcpport=50931&localrtcpport=50931&pkt_size=188':
0|homebridge  |   Metadata:
0|homebridge  |     encoder         : Lavf58.26.100
0|homebridge  |     Stream #0:0: Video: h264 (h264_omx), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 299 kb/s, 30 fps, 90k tbn, 30 tbc
0|homebridge  |     Metadata:
0|homebridge  |       encoder         : Lavc58.44.100 h264_omx
0|homebridge  | frame=    3 fps=0.0 q=-0.0 size=       7kB time=00:00:00.03 bitrate=1642.8kbits/s dup=1 drop=0 speed=0.0452x
0|homebridge  | frame=   11 fps=7.9 q=-0.0 size=      15kB time=00:00:00.30 bitrate= 421.9kbits/s dup=5 drop=0 speed=0.216x
0|homebridge  | frame=   19 fps=9.8 q=-0.0 size=      25kB time=00:00:00.53 bitrate= 391.0kbits/s dup=9 drop=0 speed=0.274x
0|homebridge  | frame=   27 fps= 11 q=-0.0 size=      40kB time=00:00:00.80 bitrate= 405.8kbits/s dup=13 drop=0 speed=0.312x
0|homebridge  | frame=   35 fps= 11 q=-0.0 size=      43kB time=00:00:01.06 bitrate= 326.5kbits/s dup=17 drop=0 speed=0.339x
0|homebridge  | frame=   43 fps= 12 q=-0.0 size=      56kB time=00:00:01.33 bitrate= 342.1kbits/s dup=21 drop=0 speed=0.362x
0|homebridge  | frame=   51 fps= 12 q=-0.0 size=      73kB time=00:00:01.60 bitrate= 374.9kbits/s dup=25 drop=0 speed=0.376x
0|homebridge  | frame=   59 fps= 12 q=-0.0 size=      76kB time=00:00:01.86 bitrate= 334.3kbits/s dup=29 drop=0 speed=0.391x
0|homebridge  | frame=   65 fps= 12 q=-0.0 size=      86kB time=00:00:02.06 bitrate= 341.3kbits/s dup=32 drop=0 speed=0.387x
0|homebridge  | frame=   73 fps= 12 q=-0.0 size=      94kB time=00:00:02.33 bitrate= 328.3kbits/s dup=36 drop=0 speed=0.392x
0|homebridge  | frame=   81 fps= 12 q=-0.0 size=     107kB time=00:00:02.60 bitrate= 336.9kbits/s dup=40 drop=0 speed=0.399x
0|homebridge  | frame=   89 fps= 13 q=-0.0 size=     120kB time=00:00:02.86 bitrate= 341.8kbits/s dup=44 drop=0 speed=0.405x
0|homebridge  | frame=   97 fps= 13 q=-0.0 size=     125kB time=00:00:03.13 bitrate= 326.2kbits/s dup=48 drop=0 speed=0.411x
0|homebridge  | frame=  105 fps= 13 q=-0.0 size=     138kB time=00:00:03.40 bitrate= 331.6kbits/s dup=52 drop=0 speed=0.416x
0|homebridge  | frame=  115 fps= 13 q=-0.0 size=     154kB time=00:00:03.73 bitrate= 336.9kbits/s dup=57 drop=0 speed=0.424x
0|homebridge  | frame=  123 fps= 13 q=-0.0 size=     166kB time=00:00:04.00 bitrate= 340.2kbits/s dup=61 drop=0 speed=0.429x
0|homebridge  | frame=  131 fps= 13 q=-0.0 size=     172kB time=00:00:04.26 bitrate= 329.5kbits/s dup=65 drop=0 speed=0.428x
0|homebridge  | frame=  139 fps= 13 q=-0.0 size=     186kB time=00:00:04.53 bitrate= 335.3kbits/s dup=69 drop=0 speed=0.43x
0|homebridge  | frame=  147 fps= 13 q=-0.0 size=     198kB time=00:00:04.80 bitrate= 338.3kbits/s dup=73 drop=0 speed=0.431x
0|homebridge  | frame=  155 fps= 13 q=-0.0 size=     203kB time=00:00:05.06 bitrate= 327.7kbits/s dup=77 drop=0 speed=0.432x
0|homebridge  | frame=  163 fps= 13 q=-0.0 size=     219kB time=00:00:05.33 bitrate= 337.1kbits/s dup=81 drop=0 speed=0.432x
0|homebridge  | frame=  171 fps= 13 q=-0.0 size=     229kB time=00:00:05.60 bitrate= 335.0kbits/s dup=85 drop=0 speed=0.433x
0|homebridge  | frame=  179 fps= 13 q=-0.0 size=     235kB time=00:00:05.86 bitrate= 327.8kbits/s dup=89 drop=0 speed=0.434x
0|homebridge  | frame=  187 fps= 13 q=-0.0 size=     247kB time=00:00:06.13 bitrate= 330.5kbits/s dup=93 drop=0 speed=0.435x
0|homebridge  | frame=  195 fps= 13 q=-0.0 size=     263kB time=00:00:06.40 bitrate= 336.1kbits/s dup=97 drop=0 speed=0.435x
```

**Comment by KhaosT** [comment]
And it looks fine on iOS? I guess I'll update repo to allow opt-out this behavior then 😅

**Comment by ayn** [comment]
Ya, it is working on iOS and Home.app on macOS.

**Comment by KhaosT** [comment]
Great. I made the change in `0.0.16`.

**Comment by ayn** [comment]
Actually, I recompiled with x264 and upgraded to `0.0.16`, and am getting the same error as before. I will just take that out for now.

**Comment by KhaosT** [comment]
Huh, that's interesting... [This change](https://github.com/KhaosT/homebridge-nest-cam/commit/a4e7fb11fd7c93de85978ca7b640ecc330da40d1#diff-5a6cee9c5f2f6d5847da52e319ce7701R431) should no longer append the problematic x264Params if you are using `x264_omx`... but anyway, glad you have a workaround 😅

**Comment by ayn** [comment]
Spoke too soon, that didn't fix it, it's a different error:

```
0|homebridge  | Input #0, h264, from 'pipe:':
0|homebridge  |   Duration: N/A, bitrate: N/A
0|homebridge  |     Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 15 fps, 15 tbr, 1200k tbn, 30 tbc
0|homebridge  | : No such file or directory
```

**Comment by KhaosT** [comment]
Oops, can you print `ffmpegCommand` before this line `let ffmpeg = spawn('ffmpeg', ffmpegCommand.split(' '), {env: process.env});`? Something like `console.log(ffmpegCommand)`.
(sorry for the problem...)

**Comment by ayn** [comment]
ya i think it's just an error in the command line, trying something here, will let you know.

**Comment by ayn** [comment]
Amazingly, the problem is an extra space in front of `-vf` when `x264Params` is an empty string.

changing it to this fixed it:

```
      let x264Params = '';
      if (self.ffmpegCodec === 'libx264') {
        x264Params = '-x264-params "intra-refresh=1:bframes=0" ';
      }

      let ffmpegCommand = '-i - -vcodec ' + self.ffmpegCodec + ' -an -pix_fmt yuv420p -r '+ fps +' -f rawvideo ' + x264Params + '-vf scale='+ width +':'+ height +' -b:v '+ bitrate +'k -payload_type 99 -ssrc '+ videoSsrc +' -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params '+videoKey.toString('base64')+' srtp://'+targetAddress+':'+targetVideoPort+'?rtcpport='+targetVideoPort+'&localrtcpport='+targetVideoPort+'&pkt_size=188';
```

**Comment by KhaosT** [comment]
😅okay I'll make the fix...

**Comment by KhaosT** [comment]
`0.0.17` should fix the space issue :)
