### ISSUE TITLE
Nest Password Requirements

### ISSUE THREAD

**Issue by patro85** [KhaosT/homebridge-nest-cam#55]
In the *How to get an Access Token* section of the main page there is no mention of password requirements or limitations. 

After much frustration and trial and error, I discovered via a comment on [Reddit](https://www.reddit.com/r/homebridge/comments/aau788/help_please_unable_to_setup_homebridgenestcam/) that you need to have a password that does not include any special characters (in spite of this being a perfectly acceptable password configuration for Nest). For those of us who use a password manager that auto generates passwords, not knowing that you need to specify no special characters is a critical piece of getting this Homebridge integration working.

**Recommended Fix**: Update documentation for *How to get an Access Token* to include information about password requirements/restrictions.

**Comment by kriscmore** [comment]
> In the _How to get an Access Token_ section of the main page there is no mention of password requirements or limitations.
> 
> After much frustration and trial and error, I discovered via a comment on [Reddit](https://www.reddit.com/r/homebridge/comments/aau788/help_please_unable_to_setup_homebridgenestcam/) that you need to have a password that does not include any special characters (in spite of this being a perfectly acceptable password configuration for Nest). For those of us who use a password manager that auto generates passwords, not knowing that you need to specify no special characters is a critical piece of getting this Homebridge integration working.
> 
> **Recommended Fix**: Update documentation for _How to get an Access Token_ to include information about password requirements/restrictions.

Thank you for posting this!!! Wasn't sure why this plugin was killing my Homebridge setup after I updated it, but now I know why.

**Comment by KhaosT** [comment]
Changing password should really not be necessary if you can properly enter the value in the format bash wants...
