### ISSUE TITLE
One of Three Cameras Missing

### ISSUE THREAD

**Issue by tobeychris** [KhaosT/homebridge-nest-cam#56]
Hi - I am having an issue where I had three cameras previously connected, but one of them dropped off.
I tried to re-add it by itself, but could not. I removed the other two Nest-cam devices and when I go to add them back, I still only see two of three.

When I run homebridge I see this:
```
[1/2/2019, 11:04:48 PM] Homebridge is running on port 51826.
[1/2/2019, 11:04:49 PM] [Nest-cam] Create camera - Baby Room
[1/2/2019, 11:04:49 PM] [Nest-cam] Create camera - Front  Door
[1/2/2019, 11:04:49 PM] [Nest-cam] Create camera - Garage
[1/2/2019, 11:04:49 PM] Baby Room is running on port 29249.
[1/2/2019, 11:04:49 PM] Front  Door is running on port 29320.
[1/2/2019, 11:04:49 PM] Garage is running on port 37943.
```
I can add the Front Door and Garage cameras, but not Baby Room.

Any ideas?

**Comment by KhaosT** [comment]
Maybe try manually remove the camera and add it again?

**Comment by dpyy** [comment]
This is exactly my issue how did you fix it?

**Comment by ddorato** [comment]
Same issue here.

**Comment by tobeychris** [comment]
Removing all of the cameras and adding them again seemed to have no effect. Wiped my config and started fresh and still nothing. I upgraded to the latest versions of everything and still nothing. I tried again the next night and magically all of the cameras were there. Sadly, that is not much help.

**Comment by ddorato** [comment]
Great...I deleted my only camera and now nothing is showing up.  Guess I’l just try rebooting to see what happens.

Seems totally random.

**Comment by dpyy** [comment]
ddorato how did you fix it?
