### ISSUE TITLE
[Nest-cam] Initializing Nest-cam platform... [NestCam]Failed to request access token. Unexpected API Error - 403

### ISSUE THREAD

**Issue by staticfade** [KhaosT/homebridge-nest-cam#59]
I am currently running the latest version of nest-cam and ffmpeg. I continue to get the following error:
[Nest-cam] Initializing Nest-cam platform...
[NestCam]Failed to request access token. Unexpected API Error - 403

I have gone through the 2 factor auth and got a access_token and have put this info into my config.json file which looks like this...
"platform" : "Nest-cam",
"access_token":"c.Qjtxxxxxxxxxxxx",
"useOMX": false

I also used the nest plugin and it finds all my nest devices but I still cannot get the nest-cam to work. any help would be greatly appreciated

**Comment by KhaosT** [comment]
If there are multiple access tokens, make sure you use the one start with `b.`

**Comment by gtstein** [comment]
I'm getting the same error but I don't see an access token starting with a "b". I'm getting the following:

"access_token":"lQkANQE.......

**Comment by staticfade** [comment]
@KhaosT I started from scratch again.  Went to developer.nest.com.  Deleted the oauth item and created a new one.  I gave permissions to my cameras and my nest protects.  I got the new client ID and secret and used the curl command to get a new auth-token...it came back with one that started with c.xxxx again.  and when restarting (post changes to my config.json file to reflect the new info from nest) I get the same error.

**Comment by KhaosT** [comment]
@gtstein you are using the wrong one, if you issue request via `https://home.nest.com/session`, there may have 2 `access_token` in there, use the first one in response, instead of the last one.

@staticfade Ah, it's a different access token. The one you requested from developer.nest.com doesn't have permission to access Nest's camera related endpoints. Please follow the readme and get an access token as a mobile client and use that.

**Comment by staticfade** [comment]
@KhaosT that was it...thanks!  When I add the cameras manually it (the Home app on iOS) asks for a code for each camera.  Is that somewhere in the documentation?

**Comment by KhaosT** [comment]
It’s the same code as your main homebridge instance.

**Comment by staticfade** [comment]
@KhaosT yeah I figures that out and edited my comment but I guess you saw it before I could change it.  Now on to my next issue with the Error:spawn ffmpeg ENOENT error.  I am running on macOS, I installed ffmpeg through command line but for some reason it kills homebridge with that error.  Trying to find a wiki for ffmpeg for macos, most are for RaspPi

**Comment by KhaosT** [comment]
ENOENT means we can’t find ffmpeg binary to run. Make sure the installation is accessible by homebridge.

**Comment by staticfade** [comment]
@KhaosT yep I have been reading about this error, trouble for me is I have tried installing ffmpeg several different ways, but I cannot seems to get homebridge to see that I installed it.  Most of what I am finding pertains to Raspberry PIs
