### ISSUE TITLE
Can No Longer add Cameras in Home App

### ISSUE THREAD

**Issue by greztaylor** [KhaosT/homebridge-nest-cam#61]
I finally got this plugin working.......but my Nest Cameras then stopped working (unable to stream) so foolishly I deleted them from the Home app in an effort to resolve.  

Now when I try re-add the Nest Cameras in the Home app they don't appear under 'Add Accessory' selecting 'Don't Have a Code or Can't Scan'.

Randomly two camera's do show but not the one's I previously added that I'm interested in adding to the home app!!!

It's as if my Homebridge has 'cached' the previously configured cameras and now I can't re-add them.  Any help would be greatly appreciated

**Comment by jscottmiller** [comment]
Were you able to resolve this? I'm running into the same and neither deleting the Home from HomeKit or resetting Homebridge data is working.

**Comment by dpyy** [comment]
Please tell me how to fix this!!
