### ISSUE TITLE
motion sensor not working

### ISSUE THREAD

**Issue by ngrimes08** [KhaosT/homebridge-nest-cam#64]
in addition to live stream not working, the motion isn't picked up either, homekit does not say no response, but its not working as i get no notification or my automation also does not trigger.

**Comment by KhaosT** [comment]
This plugin does not offer motion sensing capability.

**Comment by ngrimes08** [comment]
Did it use to? Because before the new required access token I used to have a working motion sensor with my camera. That’s how i got my outside lights to turn on at night

**Comment by KhaosT** [comment]
This one never wired up for motion. I guess you were also using the other Nest plugin?
