### ISSUE TITLE
[NestCam] Failed to request access token. Unexpected API Error - 403 again

### ISSUE THREAD

**Issue by wjkie** [KhaosT/homebridge-nest-cam#69]
I have an access token and the cams were visible and working in the Home app. Seems like the software on the cam was updated to 223-610050 recently and for the last 2 days the camera has not been responding. I am now getting the following error 
"[NestCam]Failed to request access token. Unexpected API Error - 403"

Google Nest indicates that the update was to disable turning off the status light on the camera as a privacy measure.  I think the update must have changed the API such that Homebridge Nest-Cam no longer works.  Does anyone else have this problem?

Any help would be appreciated.

**Comment by kitknox** [comment]
My cameras are running that software and are still working with HomeBridge.  I'm still on a Nest account with 2FA.

**Comment by wjkie** [comment]
I too have a 2FA account not sure what is different.  I am going to reinstall to see if that solves the problem

**Comment by wjkie** [comment]
Well all is fixed.  For some reason the access token changed on nest. I copied the new one changed it in the config.json file, rebooted my raspberry pi and now all is well.  Go figure.
