### ISSUE TITLE
Crash when trying to open camera

### ISSUE THREAD

**Issue by ikolsteren** [KhaosT/homebridge-nest-cam#8]
When I try to open either one of the cameras I get a crash
/usr/local/lib/node_modules/homebridge-nest-cam/lib/streamer.js:139 
requestBuffer = Buffer.concat([requestBuffer, Buffer.from(buffer)]);

TypeError: this in not a typed array

I have useOMX false and installed ffmpeg
not sure what I am missing
I am running on Ubuntu VM

**Comment by KhaosT** [comment]
What’s the node version?

**Comment by ikolsteren** [comment]
I assume via node -v
then v4.2.6

**Comment by KhaosT** [comment]
This plugin has a minimal node dependency of 8.x …

**Comment by ikolsteren** [comment]
Ok just added the source and upgraded to 8
Now I get the following and homebridge dies
/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

**Comment by KhaosT** [comment]
Node module binding is version dependent. After update node, you need to make sure to rebuild those modules.

**Comment by JJJ** [comment]
> After update node, you need to make sure to rebuild those modules.

In other words, anytime you upgrade Node you'll need to go through the HomeBridge installation steps again. Once you do this, everything should hopefully start working for you.

**Comment by ikolsteren** [comment]
Looks like I got figured out last night and is working well
