### ISSUE TITLE
Any plans to make this work post-Google migration? Currently seems to be useless

### ISSUE THREAD

**Issue by soulcook** [KhaosT/homebridge-nest-cam#80]
Six months ago Google announced the end of separate Nest logins and a migration to authentication via Google. More and more Nest users now use Google authentication, and before long almost all will. 

But it seems that this plugin as it stands is useless post-migration, since its token-based authentication is no longer appropriate. I’ve had to stop using it, as I’m sure have many others. 

Any plans to fix this (as has already been done for homebridge-nest)?

**Comment by Brandawg93** [comment]
I am continuing this project [here](https://www.npmjs.com/package/homebridge-nest-cam2). Google authentication has been resolved.

**Comment by soulcook** [comment]
Great news. Thank you!

**Comment by soulcook** [comment]
Great news. Thank you!

**Comment by soulcook** [comment]
Great news. Thank you!
