### ISSUE TITLE
Decrease thumbnail regeneration time

### ISSUE THREAD

**Issue by JJJ** [KhaosT/homebridge-nest-cam#9]
It looks like thumbnails are regenerated every 10 seconds, but I'm not able to see how to change this.

I'd like to decrease this to something like 5 or 3. Perhaps even as part of `config.json`?

**Comment by KhaosT** [comment]
We are just making request when HomeKit ask us to do so. There is no way for accessory proactively send image to HomeKit.

**Comment by JJJ** [comment]
I just figured this out. Thanks for the reply; sorry for the issue noise.
